management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
  server:
    port: 8080
  endpoint:
    health:
#      show-details: always
      show-components: always
#    shutdown:
#      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
      base-path: "/actuator"
info:
  app:
    name: hello-actuator
    company: yh

logging:
  level:
    hello.controller: debug
