management:
  endpoint:
    health:
#      show-details: always
      show-components: always
#    shutdown:
#      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
